### ISSUE TITLE
default location on windows

### ISSUE THREAD

**Issue by apiszcz** [pvpscript/mpv-video-splice#9]
I am unable to locate the tmp or out folders on windows even though they are set in my environment variables?

Does LUA hand Windows folder using ~/ ? did not see the output or folders in my home directory either

```
local SCRIPT_NAME = "mpv-splice"
local default_tmp_location = "~/tmpXXX"
local default_output_location = mp.get_property("working-directory")

local splice_options = {
	tmp_location = os.getenv("MPV_SPLICE_TEMP") and os.getenv("MPV_SPLICE_TEMP") or default_tmp_location,
	output_location = os.getenv("MPV_SPLICE_OUTPUT") and os.getenv("MPV_SPLICE_OUTPUT") or default_output_location
}
opt.read_options(splice_options, SCRIPT_NAME)
```

**Comment by Kyomari** [comment]
In Windows, the tilde character (~) is not used to refer to the user's home directory. Instead, the home directory is typically located at "C:\Users<username>".

Regarding the issue of not being able to locate the tmp or out folders, it is possible that the folders have not been created yet. The code you provided is defining the default locations for these folders, but it does not actually create them. You may need to add code to your script that creates the tmp and out folders if they do not already exist.

Alternatively, you could try specifying an absolute path for the tmp and out folders instead of using environment variables. For example, you could set default_tmp_location to "C:/tmpXXX" and default_output_location to "C:/path/to/output/folder".

**Comment by apiszcz** [comment]
Thank you for making this capability, i have tried everything you recommended and am still having issues. I will look into it more

**Comment by apiszcz** [comment]
```
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> os.getenv("HOME")
nil
> os.getenv('USERPROFILE')
C:\Users\username
```

**Comment by pvpscript** [comment]
First of all, sorry about the very late response. I'll be picking up this project again and making it compatible with Windows. https://github.com/pvpscript/mpv-video-splice/issues/12

**Comment by pvpscript** [comment]
I've done some work on the code, it should work on Windows now!
